### ISSUE TITLE
"IndexError: list index out of range" when sending command "heroku run worker"

### ISSUE THREAD

**Issue by gwingle** [tommeagher/heroku_ebooks#14]
The error is as follows:
```
Running worker on safe-earth-67442.... up, run.1755
Traceback (most recent call last):
  File "ebooks.py", line 79, in <module>
    source_tweets_iter, max_id = grab_tweets(api,max_id)
  File "ebooks.py", line 51, in grab_tweets
    max_id = user_tweets[len(user_tweets)-1].id-1
IndexError: list index out of range
```

These are my settings with keys left out:
```
SOURCE_ACCOUNTS = ["GwingleWizard", "Darkstr_", "badsums", "belly_rose", "noh_jgjb", "loserice", "andrewhussie", "billwurtz", "kanyewest", "berniethoughts", "sylferino", "sass_o_matic", "boburnham", "wolfpupy"] #A list of comma-separated, quote-enclosed Twitter handles of account that you'll generate tweets based on. It should look like ["account1", "account2"]. If you want just one account, no comma needed.
ODDS = 1 #How often do you want this to run? 1/8 times?
ORDER = 2 #how closely do you want this to hew to sensical? 1 is low and 3 is high.
DEBUG = True #Set this to False to start Tweeting live
STATIC_TEST = False #Set this to True if you want to test Markov generation from a static file instead of the API.
TEST_SOURCE = ".txt" #The name of a text file of a string-ified list for testing. To avoid unnecessarily hitting Twitter API.
TWEET_ACCOUNT = "GwingleBot" #The name of the account you're tweeting to.
```

**Comment by tommeagher** [comment]
Hi @gwingle, my guess is that this failure is related to issue #6. For now, try it only with accounts that have more than 3600 tweets in them.

**Comment by gwingle** [comment]
Definitely seems like that was the issue. Unfortunately, it looks like I won't be able to include my own account.

**Comment by tommeagher** [comment]
I'm sorry about that. This is a good impetus for me to push #6 higher on my list of priorities. It might not be tomorrow, but I'll try to get that knocked out, if you want to keep an eye on that issue. In the meantime, I'll close this one as duplicative. Thanks for the bug report!
