### ISSUE TITLE
heroku run worker not producing anything

### ISSUE THREAD

**Issue by taibt** [tommeagher/heroku_ebooks#18]
(caveat, I am not super familiar with coding jargon)

I get this error every few times I run the heroku run worker command:

Traceback (most recent call last):
  File "ebooks.py", line 77, in <module>
    handle_stats = api.GetUser(screen_name=user)
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 2908, in GetUser
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 4862, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 4882, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{u'code': 32, u'message': u'Could not authenticate you.'}]

The other times, I get the # No, sorry, not this time error.

My app permissions are set to read and write in dev. I also set ODDS to 0 yet I keep getting both error messages. I'm not sure what to do to make my bot work. The account I'm pulling from is one I've had forever and has 92k tweets.

Thanks in advance!

**Comment by tommeagher** [comment]
Hi @taibt. Are you sure you're using the correct credentials in your local_settings.py ? Also, you should try setting ODDS to 1 or 2 and see if that helps.
