### ISSUE TITLE
 u'Could not authenticate you.', u'code': 32

### ISSUE THREAD

**Issue by marcodionisio** [tommeagher/heroku_ebooks#31]
Hi! I'm not familiar with Python so I'm having a hard time trying to fix this error.

Running worker on pure-badlands-73935... up, run.3341 (Free)
Traceback (most recent call last):
  File "ebooks.py", line 78, in <module>
    handle_stats = api.GetUser(screen_name=user)
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 2928, in GetUser
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 4894, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/app/.heroku/python/lib/python2.7/site-packages/twitter/api.py", line 4914, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{u'message': u'Could not authenticate you.', u'code': 32}]

Thanks!

**Comment by tommeagher** [comment]
Hi @marcodionisio. Did you follow steps 1-6 in the [README](https://github.com/tommeagher/heroku_ebooks#setup)?  It looks like you didn't put your API credentials in a local_settings.py file.
