### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alikoneko** [tommeagher/heroku_ebooks#52]
Hi. I was able to get the bot working once and then after fixing something custom for the theme of my ebooks account, I have either been getting the "x, No, sorry, not this time." error or this Index error, I do see the bot grabbing tweets though. Is this related to the low-tweet count?

```
Traceback (most recent call last):
  File "ebooks.py", line 203, in <module>
    ebook_status = mine.generate_sentence()
  File "/app/markov.py", line 58, in generate_sentence
    restup = (res[-2], res[-1])
IndexError: list index out of range
```

```
1394 tweets found in boredelonmusk
2360 tweets found in tesla
4604 tweets found in spacex
5405 tweets found in elonmusk
5657 tweets found in dogecoin
6867 tweets found in Dogebrarian
```

**Comment by alikoneko** [comment]
I'm closing this as I have found and fixed the issue. The order variable can't be 1 and I didn't realize it.
